forma_de_publicacion = TagType.find_by_name("Institución")
Tag.create(name: "Presidencia", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "Congreso Nacional", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "Junta Militar", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "Asamblea Constituyente", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "CNBS", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "Municipalidad de SPS", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "SENASA", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "Aduana", tag_type_id: forma_de_publicacion.id)
Tag.create(name: "CREE", tag_type_id: forma_de_publicacion.id)