Stripe.api_key = ENV['STRIPE_SECRET_KEY']

BASE_PRICE_MONTHLY = 12.00
BASE_PRICE_SEMESTRAL = 64.00
BASE_PRICE_ANNUALLY = 115.00
BASE_PRICE_STUDENT = 10.00
MONTHLY_PRICE_ANNUALLY = 9.60
MONTHLY_PRICE_SEMESTRAL = 10.80
ENTERPRISE_PRICE = 40.00

if Rails.env.development?
  STRIPE_PUBLIC_KEY = "pk_test_51H0sbTJDCreTdC1MiTmXgtca69vY4PqnUcbBLHTufp3dG2csCmxSOYq24Iw3ukIc64XllTaubTM4IrnCxNYMlBqZ00fMpYKMTR"
  STRIPE_SUBSCRIPTION_PRODUCT = "prod_HmWdVtbJ5fEFkU"
  STRIPE_MONTH_SUBSCRIPTION_PRICE = "price_1HCxa9JDCreTdC1MjLhqrSeW"
  STRIPE_SEMESTER_SUBSCRIPTION_PRICE = "price_1KjuWiJDCreTdC1Mlb62wDUa"
  STRIPE_YEAR_SUBSCRIPTION_PRICE = "price_1HCxa9JDCreTdC1M2wVLCYG0"
  STRIPE_STUDENT_SUBSCRIPTION_PRICE = "price_1KjuJKJDCreTdC1M7AMR9t4w"
elsif Rails.env.production?
  STRIPE_PUBLIC_KEY = ENV['STRIPE_PUBLIC_KEY']
  STRIPE_SUBSCRIPTION_PRODUCT = ENV['STRIPE_SUBSCRIPTION_PRODUCT']
  STRIPE_MONTH_SUBSCRIPTION_PRICE = ENV['STRIPE_MONTH_SUBSCRIPTION_PRICE']
  STRIPE_YEAR_SUBSCRIPTION_PRICE = ENV['STRIPE_YEAR_SUBSCRIPTION_PRICE']
end