institucion = TagType.find_by_name("Institución")
Tag.create(name: "Poder Ejecutivo", tag_type_id: institucion.id)
Tag.create(name: "Congreso Nacional", tag_type_id: institucion.id)
Tag.create(name: "Junta Militar", tag_type_id: institucion.id)
Tag.create(name: "Asamblea Constituyente", tag_type_id: institucion.id)
Tag.create(name: "CNBS", tag_type_id: institucion.id)
Tag.create(name: "Municipalidad de SPS", tag_type_id: institucion.id)
Tag.create(name: "SENASA", tag_type_id: institucion.id)
Tag.create(name: "Aduana", tag_type_id: institucion.id)
Tag.create(name: "CREE", tag_type_id: institucion.id)