tipo_de_acto = TagType.create(name: "Tipo de Acto")
tema = TagType.create(name: "Tema")
forma_de_publicacion = TagType.create(name: "Forma de Publicación")
institucion_emisora = TagType.create(name: "Institución Emisora")
instituciones_relacionadas = TagType.create(name: "Instituciónes Relacionadas")
#TagType.create(name: "Territorio")