tag_type_institution = TagType.find_by_name('institucion')

Tag.create({ name: 'SEIP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SGYJ', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CSJ', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INFOP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ministerio de la Presidencia', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'UNAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BCH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PANI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'HONDUTEL', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ENEE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SANAA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BANASUPRO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ENAG', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CNBS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONATEL', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ministerio Público', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IAIP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONADEH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'TSE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PGR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corte de Apelaciones', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Educación', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Salud', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Seguridad', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado del Despacho Presidencial', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Relaciones Exteriores', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en el Despacho Defensa Nacional', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SEFIN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SIC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SOPTRAVI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Trabajo y Seguridad Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SAG', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SERNA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Desarollo Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SEPLAN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SCAD', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Turismo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de la Juventud', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Pueblos Indígenas y Afrohondureños', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FHIS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Instituto Nacional de la Mujer', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PRAF', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ICF', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'UPNFM', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHSS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INJUPEMP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Lamaní, Comayagua', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Comayagua', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en los Despachos de Justicia y Derechos Humanos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'UNCIH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PRONADERS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fundacion PROLANCHO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección General de Propiedad Intelectual', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INPREMA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FOSEDE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PCM', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Lejamani, Comayagua', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DEI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Minas de Oro, Comayagua', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión para la Defensa y Promoción de la Competencia', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Multisectorial de Emergencia, Fortalecimiento Fiscal y Equidad Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CCIVS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'RNP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CNE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ESNACIFOR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AMDC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Belen, Lempira', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DGSC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IPM', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'TSC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHDECOOP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CIFH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Sonaguera, Colón', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHADFA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'RAP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de La Ceiba, Atlantida', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Roatán, Islas de la Bahia', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Catacamas, Olancho', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DGMM', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DEFOMIN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BANADESA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONAPID', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Consejo Central Ejecutivo del Partido Liberal', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Trujillo, Colón', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'HBCBH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Abogados de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Rosa de Copán, Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CENEMEC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CMH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Siguatepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'APO-AUTIS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COPECO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Presidencia de la República de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de San Buenaventura', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ENP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Plan de Arbitrios de Siguatepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ONCAE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Superintendecia de Alianza Público Privada', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Universidad Nacional de Agricultura', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Integración Económica Centroamericana', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FEHDEBOX', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DINADERS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad  de Colosuca Gracias, Lempira Honduras C.A.', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INPREUNAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Pedro Sula', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ZOLITUR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Economía y Hacienda', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Ingenieros Civiles de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONDEPAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Concepción, Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fondo Vial', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad PUCA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'MANOFM', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Roatán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gobernador Departamental de La Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa de Administración de Tierras de Hnduras PATH-II', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COMIECO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'EDUCREDITO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COLPROSUMAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa de Conversión de Deuda de la Deuda de Honduras Frente a España', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Las Vegas, Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'La Armería', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Partido Nacional de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BCIE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'OIRSA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Guanaja', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ASHONPLAFA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BANHPROVI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Universidad Nacional de Agricultura Catacamas, Olancho, Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COLPEDAGOGOSH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DICTA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Hospital Escuela Universitario', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad CAFEG', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHMA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaria General de la Super Intendencia de la Alianza Publica Privada', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Especial de Transición del Sistema Nacional Penitenciario', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Arquitectos de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de La Labor', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaria Departamental de Francico Morazán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'JTNCA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de La Esperanza', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONACAFE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Peritos Mercantiles y Contadores Públicos de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Cámara Hondureña de la Industria de la Construcción', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Marcos de Ocotepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COLPROFORH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AMFI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de José Santos Guardiola de Islas de la Bahía', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Sistema de la Integración Centroamericana (Unidad Regional de Pesca y Acuicultura)', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Periodistas de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Superintendencia de Concesiones y Licencias', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FEHNA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ONADICI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FENATH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COLPROCAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Instituto de la Propiedad Industrial', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'HONDUCOR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AMHON', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Banco ProCredit Honduras, S.A.', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FEHDERACQUET', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fuerzas Armadas de Honduras Estado Mayor Conjunto', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AIF', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Choloma', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Interairports', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Choluteca', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONAMARH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CIAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Gracias, Lempira', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FEHMISSE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de la Gobernacion de Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COHEP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Santa Fe, Colon', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ERSAPS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COHCIT', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Economía', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Bonito Oriental, Colón', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FENASOBH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FMI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PASS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SITRAPANI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INJ', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHCAFE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Nacional Para el Desarrollo de la Educación Alternativa no Formal', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ANEEAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en los Despachos de Desarrollo Económico', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FPOSC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Ojojona', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en los Despachos de Derechos Humanos, Justicia, Gobernación y Descentralización', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Antonio de Oriente', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Lorenzo Valle', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AFE-COHDEFOR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Protección, Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PRICPHMA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DGAC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONASA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CAP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IDECOAS', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de La Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INSEP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio Quimico Farmaceuticos de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AFH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corporación Municipal de Dulce Nombre de Culmí, Olancho', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Francisco de Ojuera, Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisionado Presidencial para la Reducción de la Pobreza', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'BID', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'AACIMH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Olanchito, Yoro', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Energía, Recursos Naturales, Ambiente y Minas', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Utila, Islas de la Bahía', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Despacho Ministro Asesor en Asuntos de Vivienda', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Contaduría General de la República', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Andrés, Lempira', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corte Interamericana de Derechos Humanos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comité Técnico del Fideicomiso', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FONAPROVI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FOSOVI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FUNDESUR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Consejo de la Judicatura y de la Carrera Judicial', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Desarrollo e Inclusión Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONSUCOOP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'MAFRON', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Villanueva, Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INHGEOMIN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Coordinación General de Gobierno', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección de Investigación y Evaluación de la Carrera Policial', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Gobernabilidad y Descentralización', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Desarrollo e Inclusión Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Desarrollo Económico', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Infraestructura Productiva', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Conducción y Regularización Económica', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gabinete Sectorial de Seguridad y Defensa', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Sector de Relaciones Internacionales', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'U-ESNACIFOR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Ana, Francisco Morazán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DINAF', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de San Marcos, Ocotepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Cruz de Yojoa, Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CFR-SICA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Profesionales de Enfermería de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHT', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Instituto de Previsión Social del Profesional del Derecho', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Contraloría General de la República', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Consejo Nacional Agrario', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SETCO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Rita (Yoro)', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COPRUMH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección Nacional De Investigación e Inteligencia División De Seguridad Aeroportuaria', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Dolores Merendon (Ocotepeque)', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santos Guardiola, Islas de la Bahía', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaria del Juzgado de Letras Tercero de lo Civil', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección de Probidad Administrativa', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaria Ejecutiva del Consejo de Ministros', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CREE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de las Flores, Lempira', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INHFA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municpal de Tela', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Consejo Nacional de Educación', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Francisco del Valle', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Direccion Ejecutiva de Cultura Artes y Deportes', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Hacienda y Crédito Público', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección General de Carreteras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FOSE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Gobernador de Santa Barbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Limón, departamento de Colón', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'MUNICIPALIDAD DE MORAZÁN, YORO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en los Despachos de Energía, Recursos Naturales, Ambiente y Minas', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corte Interamericana de Dechos Humanos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Tribunal Nacional de Elecciones', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de la Villa de San Francisco', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal de Puerto Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ferrocarril Nacional de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad de Municipions Valle de Senseti, Departamento de Ocotepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Banco Municipal Autónomo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SECOP', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección General de Conservación de Carreteras y Aeropuertos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Economía y Comercio', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Industria, Comercio y Turismo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COMRIEDRE V', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ministerio de Obras Públicas y transporte', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corporación Municipal de la Lima Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corporación Municipal de San Manuel, Departamento de Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de Choloma Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FINSA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisionada Presidencial Administración Tributaria', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fundacion Vive Mejor', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal El Nispéro, Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Juzgado de Letras Seccional de la ciudad de Trujillo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de La Paz, La Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad de Municipios del Sur, Departamento de la Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Procuraduría del Ambiente y Recursos Naturales', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'MUNICIPALIDAD VILLA DEL CARMEN EL NEGRITO, DEPARTAMENTO DE YORO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Trojes, Departamento del Paraiso', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corporacion Municipal de Choloma, Departamento de Cortes', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Fraternidad Departamento de Ocotepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Presidencial de Modernización del Estado', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Infraestructura y Servicios Públicos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'UNICAH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fundación Promejoramiento del Hospital San Lorenzo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Talanga, Departamento de Francisco Morazán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Rosa de Aguan', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PAC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Tatumbla, Departameento de Francisco Morazán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'COPRISAO', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría Ejecutiva del Consejo de Ministros', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SAR', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldía Municipal de Santa Rosa de Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Psicólogos de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FONAC', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Desarrollo Económico', tag_type_id: tag_type_institution.id })
Tag.create({ name: '911', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SENASA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de la Unión Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fundación de Apoyo Hospital San Lorenzo', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHTT', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'UNH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de San Pedro Zacapa, Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de EL Negrito, Yoro', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INADI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ministerio de Gobernacion y Justicia', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Federacion Nacional de Boliche de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Puerto Cortés', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Juzgado de Letras Civil de Francisco Morazán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Nacional Electoral del Partido Nacional de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Instituto Nacional de Migración', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de La Unión, Departamento de Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'PDCH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Agencia Hondureña de Aeronáutica Civil', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Agencia de Regulación Sanitaria', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión de Escalafón Diplomatico y Consular', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Nacional de Prevención,  Rehabilitación y Reinserción Social', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Corporación Hondureña de Desarrollo Forestal', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Universidad de Defensa de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Ministerio de Economia y Comercio', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Dirección Ejecutiva del Catastro', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Instituto de la Propiedad Unidad Especial de Expropiaciones', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Alcaldia Municipal De El Negrito Departamento de Yoro', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Estado en los Despachos de Economía, Industria y Comercio', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Especial para el Proceso de Depuración y Transformación de la Policia Nacional', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SGJD', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Santa Fe, Departamento de Colón', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FENAFUTH', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'IHCIETI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CODIPANI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Veracruz, Departamento de Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Dulce Nombre de Culmi', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mancomunidad de Municipios del Norte de El Paraíso', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Marcala, Departamento de la Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Danlí (Departamento del Paríso)', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Hospital Psiquiatrico Dr. Mario Mendoza', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Ceguaca, Departamento de Santa Bárbara', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Apoyo a la Presidencia', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DNII', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Médicos Veterinarios de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Derechos Humanos', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'SEN', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'INAMI', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DIDADPOL', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Presidencial de Becas Honduras 20/20', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fundación de Apoyo al Hospital Dr. Mario Catarino Rivas', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Corquín, departamento de Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Presidencial Ciudad Mujer', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'MANCURISJ', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comisión Interinstitucional Contra La Explotación Sexual, Comercial y Trata de Personas de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'DARA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Mecanismo Nacional de Prevención Contra la Tortura', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'ASIDE', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comayagua', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Cucuyagua, Departamento de Copán', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'CONVIVIENDA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Secretaría de Cultura', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad De Juan Francisco Bulnes, Gracias a Dios', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Colegio de Profesionales de Administración Pública de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Mercedes de Oriente, La Paz', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Juan Francisco Bulnes, departamento de Gracias a Dios', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Piraera, Lempira', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Programa Presidencial Credito Solidario', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FUSINA', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Fondo de Previsión Social de los Notarios', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Unidad Municipal Desconcentrada Aguas de Siguatepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Federación Nacional De Judo De Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Administración Aduanera de Honduras', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Municipalidad de Belén Gualcho Ocotepeque', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'Comité Nacional de Protección Forestal, de Áreas Protegidas y Vida Silvestre', tag_type_id: tag_type_institution.id })
Tag.create({ name: 'FUNDAGES-HEAC', tag_type_id: tag_type_institution.id })